### ISSUE TITLE
Songs not playing after OS upgrade

### ISSUE THREAD

**Issue by soumyatheman** [headsetapp/headset-electron#475] opened 2022-05-05 08:57 UTC
### Description

3 days ago I updated my Ubuntu from 21.10 to 22.04. After upgrading, I tried headset and no song plays from then, everything else works well but the songs are not playing.

### Expected behaviour

The songs would have played normally.

### Actual behaviour

The songs are not playing, let's say you searched for a song, it shows all the results, but clicking them doesn't play them, it only shows the player.

### Your Environment

- What OS are you using? Ubuntu 22.04
- What version of Headset? (copy and paste from the user profile page if possible) Core: v2.11.0, Wrapper: v3.3.3

### Screenshots
![Screenshot from 2022-05-05 14-16-58](https://user-images.githubusercontent.com/72045785/166891631-8d7f5b29-21f9-4e26-bb7f-fc9f22c86afe.png)

🖼

**Comment by soumyatheman** [comment] 2022-05-05 19:11
> How did you install Headset? `deb` or `snap`? Also, are you using Wayland, or X11?

Sorry for not mentioning. I'm using it as deb file obviously and it's in wayland(would have used snaps if available in wayland)

**Comment by fcastilloec** [comment] 2022-05-05 19:25
Thanks, I'm able to reproduce this, the problem is with Wayland. I can tell you that this weekend (no longer than next weekend) we'll have a new version that will support Wayland.

**Comment by fcastilloec** [comment] 2022-05-09 20:02
New version has been released and this issue should be fixed

**Closed by fcastilloec** 2022-05-09 20:02 UTC
