### ISSUE TITLE
Missing code signature in MacOS downloads (intel+arm) 4.2.0

### ISSUE THREAD

**Issue by suschizu** [headsetapp/headset-electron#512] opened 2022-08-26 18:41 UTC
### Description

code signature is missing in all macOS downloads

`codesign -dv --verbose=4 /Path/To/Application.app`

### Expected behaviour

EXPECTED code signature: 
Daniel Ravina (4BJNEK4V69)

### Actual behaviour

the app won't open without permissions

### Your Environment

macOS 12.5.1 
- What version of Headset? (copy and paste from the user profile page if possible)

**Comment by fcastilloec** [comment] 2022-08-26 18:41
Is this happening with the latest version 4.2.0?

**Comment by suschizu** [comment] 2022-08-26 18:55
I can't confirm … I receive for both variants:
`Headset-4.2.0-x64_folder/Headset.app: code object is not signed at all`
`Headset-4.2.0-arm64_folder/Headset.app: code object is not signed at all`
downloads:
https://github.com/headsetapp/headset-electron/releases/download/v4.2.0/Headset-4.2.0-x64.dmg
https://github.com/headsetapp/headset-electron/releases/download/v4.2.0/Headset-4.2.0-arm64.dmg

**Comment by fcastilloec** [comment] 2022-08-26 19:10
I see what the problem is, the CI did sign the packages, but didn't notarize them, so the end result shows as not signed.
I'll be pushing a fix for this right now.

**Comment by fcastilloec** [comment] 2022-08-26 20:03
@suschizu I new build (and eventually version) is going to be pushed in the next 20-30 mins. Would you be willing to test on your own machine for the signatures?
I've added a test on the CI but I want to be double sure that there aren't any issues before pushing a new version. I'll post the link to the new artifacts here very soon (as soon as the CI has the new files)

**Comment by fcastilloec** [comment] 2022-08-26 20:54
Here's the link to the files: https://github.com/headsetapp/headset-electron/suites/8005697404/artifacts/343194703
@suschizu can you double-check that there aren't any problems anymore?

**Closed** 2022-08-26 21:06 UTC

**Comment by suschizu** [comment] 2022-08-27 18:18
hey @fcastilloec - great thanks for the fast fix! and sorry for the late reply …
Yes - I can confirm that both downloads are now signed with
`Developer ID Application: Daniel Ravina (4BJNEK4V69)`
