### ISSUE TITLE
[FEATURE] Include the original youtube player to circumvent having 2 windows

### ISSUE THREAD

**Issue by axydavid** [headsetapp/headset-electron#116] opened 2018-01-19 14:45 UTC
### Description

The youtube policy is annoying however I feel that the current solution of having 2 windows is not a great one. Why not just including the original embedded player instead of the one that's provided now?
It's possible to just draw some text/buttons over the html5 player.

### Expected behaviour

The original player should appear instead and have some buttons/text over it.

### Actual behaviour

Now we have 2 separate players in 2 different windows that do exactly the same thing, having 2 windows is annoying.

### Your Environment

- Windows 10
- v1.6.4

### Screenshots

![image](https://user-images.githubusercontent.com/11884779/35155975-ae00cca0-fd2f-11e7-8fc2-5d478795e1b1.png)

**Comment by danielravina** [comment] 2018-01-19 15:40
Hi! Does this help? https://github.com/headsetapp/headset-electron/issues/91

**Comment by danielravina** [comment] 2018-01-19 15:44
Hi! Does this help? https://github.com/headsetapp/headset-electron/issues/91
Specifically https://github.com/headsetapp/headset-electron/issues/91#issuecomment-350591438

That being said, if you can think of a better alternative, I would love to hear it! I'm not crazy about this approach either (it also makes it technically harder) but that's the best I could come up with.

**Comment by fcastilloec** [comment] 2018-01-19 17:06
Closing the issue since it's a duplicate of #91 and there's no fix for this in the near future.

**Closed by fcastilloec** 2018-01-19 17:06 UTC
Labels: duplicate

**Comment by axydavid** [comment] 2018-01-20 18:52
Ah,
I see allright then.
