### ISSUE TITLE
Media keys support

### ISSUE THREAD

**Issue by umpirsky** [headsetapp/headset-electron#5] opened 2017-05-15 15:26 UTC
![screenshot from 2017-05-15 17-26-05](https://cloud.githubusercontent.com/assets/208957/26065256/9d4297d2-3993-11e7-961a-ea9ff156df1b.png)

**Comment by m1guelpf** [comment] 2017-05-15 15:58
:+1: for this

**Comment by danielravina** [comment] 2017-05-15 17:33
Is this specific to Linux? I'm not a Linux user so I can't tell. There's a listener to the mac media keys here: https://github.com/headsetapp/headset-electron/blob/master/index.js#L70

Perhaps if you can figure out how to integrate with other systems, you can open a PR for that? Currently, we only support `play-pause`, `play-next` and `play-previous`. Thanks!

**Comment by umpirsky** [comment] 2017-05-15 18:39
Seems so. For the reference, I was reporting similar issue to https://github.com/nukeop/nuclear/issues/18, maybe it can be useful for someone who want's to apply same logic here.

**Comment by GNOME-IS-LIFE** [comment] 2017-05-16 13:08
i believe the best way to implement keybaord keys would not be to interfere and create your own key listener, BUT instead to follow the MPRIS standard, which every other music player does. this 100% works with Linux (gnome & kde) and might also with Windows and Mac. as if you implement the MPRIS standard than we can see a notification for the song with play & pause and stop buttons in GNOME Notification centre as GNOME & KDE make FULL use of Mpris, it would amazingly help a lot of use Linux users who want YouTube music online in a music app ;) :wink:

**Comment by danielravina** [comment] 2017-05-16 15:30
Ok I understand. Problem is that the app is using the _web version_ of the YouTube embedded player. I'm not sure if this can be integrated with MPRIS. On the other hand, if there _is_ some way to pull this off, it will go against YouTube's ToS because by doing that, only the audio will be streamed (please correct me if i'm wrong).

**Comment by GNOME-IS-LIFE** [comment] 2017-05-17 09:47
wait a second. Adding MPRIS support won't magically only stream audio xD MPRIS is just giving of the play pause, forward, rewinds & album art through a specific standard widely adopted. And you stated, you are using the web version of YouTube, why not make the MPRIS support link the button functions to the button in your ui. you know, the app? and you can export the album art from your app onto MPRIS! easy!

**Comment by GNOME-IS-LIFE** [comment] 2017-05-17 09:47
and you not try to use youtube-dl? thats what Lollypop uses

**Comment by luispabon** [comment] 2017-06-09 12:14
MPRIS support would be great, should automagically integrate headset into the notification area as well as media buttons support :+1:

**Comment by fcastilloec** [comment] 2017-07-27 08:57
I had high hopes that this was going to be a feature of Headset but I was disappointed. I've been looking everywhere for a Youtube player that can be integrated to the media keys of my OS. I wish I know programming so I could contribute with this

**Comment by Tusharchoudhary** [comment] 2017-07-27 18:50
much wanted!

**Comment by danielravina** [comment] 2017-07-27 19:48
Ok guys I'll make this my highest priority to resolve this! Windows and Mac already support media keys and Linux should get some love as well. Been really busy lately :)

**Comment by fcastilloec** [comment] 2017-07-31 00:09
So after reading a lot on `globalShortcut` it seems that there's no easy fix for this. The bug goes all the way to electron and not Headset. Any other music app using electron has the exact same problem. 
The problem is that electron won't bind the shortcuts if these are being used by another app or the OS. And because the OS has bound the media buttons, electron won't bind them to its app. Instead of registering a shortcut, there should be a way to listen for an OS glocal shortcut.
I'm going to publish a workaround which will fix this issue, but the media keys will change. You'll have to press CTRL+(the media key).

MPRIS could solve the issue (sort of), but this is a more complicated way. And not all OS comes with mpris out-of-the-box. Meaning that there's going to be more dependencies when installing.

**Comment by danielravina** [comment] 2017-07-31 00:17
I'm good with that workaround. Thanks @fcastilloec!

**Comment by bil-elmoussaoui** [comment] 2017-08-05 13:52
@fcastilloec Which OS doesn't come with MPRIS? :p

**Comment by luispabon** [comment] 2017-08-07 09:57
It is OK to have tailored solutions for problems specific to certain OS.

**Comment by fcastilloec** [comment] 2017-08-11 23:43
@danielravina I think we can close this issue

**Comment by m1guelpf** [comment] 2017-08-12 10:34
Maybe we could push a new release before?

**Comment by danielravina** [comment] 2017-09-09 17:42
Fixed and available in https://github.com/headsetapp/headset-electron/releases/tag/v1.6.0-linux

**Closed by danielravina** 2017-09-09 17:42 UTC
