### ISSUE TITLE
Mac: have a choice to minimize application to dock or menu bar

### ISSUE THREAD

**Issue by abourdon** [headsetapp/headset-electron#68] opened 2017-09-19 08:47 UTC
Hi!

First of all, thanks for this useful application! I was bored to always open a dedicated tab on my browser only to listen music through Youtube... Second, thanks for providing a way to limit bandwidth for those who only use Youtube to listen music!

Just an idea to be perfect: could it be possible to have an option to choose the way to display application icon? This way we could choose to minimize application into the menu bar and hide it from the dock as it can be possible for a large amount of applications that mostly runs in background.

I think this issue could be an improvement of #8, and why not a generalisation for any OS (not only Mac for my case or Linux for #8)

Thanks!

**Comment by danielravina** [comment] 2017-12-10 23:05
Hi, sorry for the late response! 
Would you want to open a PR for that? Thanks

**Comment by abourdon** [comment] 2017-12-11 08:09
Hi,
Sorry no, I do not have much time right now...

**Comment by danielravina** [comment] 2017-12-12 05:18
no problem. It's on my todos anyways :) cheers

**Comment by fcastilloec** [comment] 2018-01-10 00:03
@danielravina Should we close this issue because #111 was open and it's just a duplicate of this one.

**Comment by danielravina** [comment] 2018-01-10 01:28
yep! it's better to handle windows and mac in one go. Thanks

**Closed by danielravina** 2018-01-10 01:28 UTC
Labels: enhancement, macOS
