### ISSUE TITLE
Ubuntu GUI.

### ISSUE THREAD

**Issue by oakniiv** [headsetapp/headset-electron#254] opened 2019-07-11 17:04 UTC
### Description

Does re-sizing and maximizing feature come with a subscription only?

### Expected behaviour

Resize. Maximize.

### Actual behaviour
Maximize and resize are blurred out as you see. Self explanatory.

![Screenshot from 2019-07-11 19-00-38](https://user-images.githubusercontent.com/34109529/61070290-994d7b00-a40e-11e9-9bd7-0eb5614829ad.png)

### Your Environment

- What OS are you using? Ubuntu 16.04
- What version of Headset? 3, freshly downloaded

P.S. You fix this and make it work on android as well, I'll subscribe for a monthly version without thinking. Also you can charge 5 bucks easily, we'll pay. Just don't go above 5 since everybody is charging 10 or more..

**Comment by fcastilloec** [comment] 2019-07-11 18:26
Headset was designed with a particular window-size in mind, that's why it can't be resized or maximized on any OSs (not just Linux). The only window that can be resized is the (hidden) player. This is by design.

**Comment by oakniiv** [comment] 2019-07-11 18:40
@fcastilloec 
I'm showing you another bug in the video. https://streamable.com/chx37
Also there is no back button to go back to the player from my profile. Just reset the app every time?

Is this a web app trying to fit many operating systems? Could work, great idea, but needs a lot of polishing.

**Comment by fcastilloec** [comment] 2019-07-11 18:49
@oakniiv I'm going to close this issue but please report the new bug on a new issue so it's easier to keep track.
Regarding the back button, when you navigate to your profile, the player gets "minimized" (becomes smaller on the lower part of the app), you can simply click there and it'll be "maximized".
![navigate](https://user-images.githubusercontent.com/1280530/61076760-d6474c80-a3d1-11e9-8537-18d5c724f662.gif)

**Closed by fcastilloec** 2019-07-11 18:49 UTC
