### ISSUE TITLE
Pressing ctrl+shift+i anywhere brings up Headset's developer tools

### ISSUE THREAD

**Issue by sab666** [headsetapp/headset-electron#284] opened 2020-02-04 10:38 UTC
### Description

When pressing ctrl+shift+i in any context, Headset's electron developer tools appear.

### Expected behaviour

For the keypress to be passed to the active application (for example Firefox or Chrome)

### Actual behaviour

Electron's developer tools pops up, pointing to https://danielravina.github.io/

### Your Environment

- What OS are you using?
Ubuntu Budgie 18.04.03
- What version of Headset? (copy and paste from the user profile page if possible)
Core: v2.8.6, Wrapper: v3.2.0

### Screenshots
![image](https://user-images.githubusercontent.com/3006667/73737393-d8447480-4742-11ea-9852-aad9f17c121a.png)

🖼

**Comment by fcastilloec** [comment] 2020-02-04 20:27
Duplicate of #281 
The fix is already in our repository, we just have to release a new version, which will happen this week.

**Closed by fcastilloec** 2020-02-04 20:27 UTC

**Comment by fcastilloec** [comment] 2020-02-04 21:04
We just released a new version, this should be fixed there. Let me know if it's fixed for you.

**Comment by sab666** [comment] 2020-02-05 09:58
Apologies for filing a duplicate and thank you for the quick reply.
As of right now there aren't any binaries available, and I'm not at liberty to setup an environment to build myself - so I'll report back once I've had a chance to test the .deb.

**Comment by fcastilloec** [comment] 2020-02-05 16:52
The binaries are up now, there was some delay due to some issues with Travis that I haven't noticed. Restarting some builds fixed everything and we're back to normal. Sorry again for the delay.

**Comment by sab666** [comment] 2020-02-06 08:53
No worries, still a marvelously fast response ;)

I can confirm that this release has fixed the issue for me. Thanks and have a great day!
