### ISSUE TITLE
Cannot use if using a proxy!

### ISSUE THREAD

**Issue by beevabeeva** [headsetapp/headset-electron#126] opened 2018-03-06 10:01 UTC
### Description

![screenshot from 2018-03-06 11-42-04](https://user-images.githubusercontent.com/19332617/37025092-b259a062-2122-11e8-88da-bcead5e9d6ef.png)

### Expected behaviour

There should be an option to enter proxy details and use it 
or inherit the system-wide proxy settings automatically

### Actual behaviour

![screenshot from 2018-03-06 11-42-04](https://user-images.githubusercontent.com/19332617/37025092-b259a062-2122-11e8-88da-bcead5e9d6ef.png)

### Your Environment

- Linux Ubuntu 17.10
- What version of Headset? (copy and paste from the user profile page if possible)

### Screenshots

🖼

**Comment by rajat-np** [comment] 2018-03-06 18:31
Possible duplicate of #3 . Please head over to this issue and see if it helps you because for now headset does not support proxies.

**Comment by fcastilloec** [comment] 2018-03-09 06:51
As @rajat-np , this is a duplicate of #3

**Closed by fcastilloec** 2018-03-09 06:51 UTC
Labels: duplicate
