### ISSUE TITLE
default cogwheel icon in notifications for new track on linux

### ISSUE THREAD

**Issue by heldderarbeit** [headsetapp/headset-electron#35] opened 2017-06-22 06:33 UTC
It would be nicer to show the application icon or the icon from the new track playing instead the default application launch icon from the desktop environment. Is this problem related to the 'Missing icon in Ubuntu' issue from the section with the known issues? Maybe there's a similar workaround.

![untitled](https://user-images.githubusercontent.com/4840355/27420295-83020b64-5725-11e7-8afa-1e07d84d6ea2.png)

**Comment by fcastilloec** [comment] 2017-07-28 19:46
@heldderarbeit I can't reproduce this at all. The notification in Ubuntu (16.04) is showing the icon for the current song. Headset app itself has an icon shown properly too.
What version of Headset are you using? what version of Ubuntu are you using? And how did you install Headset on your system? (compiled yourself, provided .deb package, etc)

**Comment by heldderarbeit** [comment] 2017-07-29 08:28
I tried it this morning again with version 1.5.4 (deb file from the website) and this issue was fixed in the meantime! the youtube preview images are now embedded correctly in the notifications.

Here is my system information for reference:

```
Deepin 4.9.29-4 (2017-07-17) x86_64 GNU/Linux
```

**Comment by fcastilloec** [comment] 2017-07-29 19:25
I guess @danielravina can close this issue too

**Comment by danielravina** [comment] 2017-07-29 20:18
Thanks @heldderarbeit and @fcastilloec!

**Closed by danielravina** 2017-07-29 20:18 UTC
