### ISSUE TITLE
Multimedia keyboard bindings.

### ISSUE THREAD

**Issue by dostiharise** [headsetapp/headset-electron#70] opened 2017-09-23 17:13 UTC
Would love to have multimedia keyboard bindings for pause/play, next and previous keys. 

I use them often during my coding sessions, so that I don't have to switch my focus to the player. Spotify Ubuntu client does it well.

**Comment by fcastilloec** [comment] 2017-09-23 17:40
@dostiharise What version of headset did you install. What's your operating system? If you're using Linux, which distro and version?
Multimedia keys have been fixed in the latest release, all the issues about that have been close (try searching close issues and you'll see).
This is a duplicate of #5 #17 #24

**Comment by danielravina** [comment] 2017-09-23 19:24
Windows + Mac supports media keys. Linux support is in 1.6.0 https://github.com/headsetapp/headset-electron/releases/tag/v1.6.0-linux

**Comment by danielravina** [comment] 2017-10-14 18:28
Fixed in https://github.com/headsetapp/headset-electron/releases/tag/v1.6.1

**Closed by danielravina** 2017-10-14 18:28 UTC
